---
- name: 'Servidor Web Apache'
  hosts: servidorwebApache
  remote_user: Javk13
  become: true
  vars_files:
    - vars/00_vars.yaml
  tasks:

    - name: 'Activando repositorio EPEL para AlmaLinux 9'
      ansible.builtin.yum:
        name: epel-release
        state: latest
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '9'

    - name: 'Instalando dependencias indicadas en 00_vars.yaml'
      ansible.builtin.yum: 
        name: "{{ paquetes }}"
        state: latest
     
    - name: 'Creando directorios indicados en 01_vars.yaml'
      ansible.builtin.file:
        path: "{{directorios}}"
        state: directory
        mode: '0755'

    - name: 'Creando credenciales b치sicas para web Apache'
      community.general.htpasswd:
        path: /home/Javk13/servidorweb/.creds
        name: usuario23
        password: 'S3rv3R'
        owner: Javk13 
        group: Javk13 
        mode: '0755'#

    - name: 'Creando clave privada de certificado'
      community.crypto.openssl_privatekey: 
        path: /home/Javk13/servidorweb/localhost.key
        size: 2048
        owner: Javk13 
        group: Javk13 
        mode: '0755'#

    - name: 'Creando petici칩n de firma para certificado'
      community.crypto.openssl_csr:
        path: /home/Javk13/servidorweb/localhost.csr
        privatekey_path: /home/Javk13/servidorweb/localhost.key
        common_name: servicio_web_caso_practico
        country_name: ES
        organization_name: Unir
        owner: Javk13 
        group: Javk13 
        mode: '0755'#

    - name: 'Generando certificado autofirmado OpenSSL'
      community.crypto.x509_certificate:
        path: /home/Javk13/servidorweb/localhost.crt
        privatekey_path: /home/Javk13/servidorweb/localhost.key
        csr_path: /home/Javk13/servidorweb/localhost.csr
        provider: selfsigned
        owner: Javk13 
        group: Javk13 
        mode: '0755'
        
    - name: 'Descargando configuraci칩n de imagen Apache desde Github'
      ansible.builtin.git:
        repo: https://github.com/javk13/ServidorWeb.git
        dest: /home/Javk13/repoWeb
                       
    - name: 'Copiando archivos imagen Apache a carpeta con certificado x509'
      ansible.builtin.copy:
        src: /home/Javk13/repoWeb/
        dest: /home/Javk13/servidorweb
        owner: Javk13 
        group: Javk13 
        remote_src: yes
        mode: '0755'

    - name: 'Autentificandose en Acr y copiando credenciales en .json'
      containers.podman.podman_login:
        username: javk13
        password: 'PYfjEDSu56eTYEGVBg6752PlWa1TARZGP0iU3hupUT+ACRCq/vw0'
        registry: javk13.azurecr.io
        authfile: etc/containers/auth.json 

    - name: 'Creando imagen y enviando al Acr'
      containers.podman.podman_image:
        build:
          cache: false
          file: /home/Javk13/servidorweb/Containerfile
        name: javk13.azurecr.io/servidorweb
        path: /home/Javk13/servidorweb
        tag: casopractico2
        push: true
        push_args:
          dest: javk13.azurecr.io 
        auth_file: etc/containers/auth.json 

    - name: 'Creando contenedor y conectando con systemd'
      containers.podman.podman_container:
        name: web
        image: javk13.azurecr.io/servidorweb:casopractico2
        authfile: 'etc/containers/auth.json'
        state: present
        ports:
          - "8080:443"
        generate_systemd:
          path: /etc/systemd/system/
          restart_policy: always
          names: true

    - name: 'Reiniciando demonio del systemd'
      ansible.builtin.systemd:
        daemon_reload: true

    - name: 'Forzando re-ejecuci칩n de systemd'
      ansible.builtin.systemd:
        daemon_reexec: true

    - name: 'Levantando contenedor desde systemd'
      ansible.builtin.systemd:
        state: started
        name: container-web.service