---
- name: 'Requisitos Web Nginx'
  hosts: servidorwebNginx
  remote_user: Javk13
  become: true
  vars_files:
    - vars/01_vars.yaml
  tasks:
  
    - name: 'Creando directorios indicados en 01_vars.yaml'
      ansible.builtin.file:
        path: "{{ directorios }}"
        state: directory
        mode: '0755'

    #- name: 'Descargando yaml con objetos del cluster desde Github'
      #ansible.builtin.git:
        #repo: https://github.com/javk13/WebAks.git
        #dest: /home/Javk13/webAKS

    - name: 'Descargando imagen desde Docker Hub'
      containers.podman.podman_image:
        name: docker.io/library/nginx 

    - name: 'Cambiando y etiquetando imagen para acr'
      containers.podman.podman_tag:
        image: nginx
        target_names:
          - javk13.azurecr.io/web_aks:casopractico2

    - name: 'Enviando imagen al Acr'
      containers.podman.podman_image:
        name: javk13.azurecr.io/web_aks
        tag: casopractico2
        push: true
        push_args:
          dest: javk13.azurecr.io 
        auth_file: etc/containers/auth.json
        pull: false

    
          
